# -*- coding: utf-8 -*-
"""#cl-ds-catencoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KebOhj_u8qyI14Wrnr4j4KhRgRpaXCyg
"""

import pandas as pd

# Load dataset
df = pd.read_csv("loan.csv")

# Identify categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", cat_cols)

# Label Encoding using pandas
for col in cat_cols:
    df[col] = df[col].astype('category').cat.codes

# One-Hot Encoding (alternative)
df_encoded = pd.get_dummies(df, columns=cat_cols)

# Save cleaned dataset
df_encoded.to_csv("cleaned_dataset.csv", index=False)